### ISSUE TITLE
bsi_bibliography.rb:77:in `include?': no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/relaton-bsi#1]
## Stack trace

<details><summary>Full stacktrace</summary>
<p>

[relaton-bsi] ("BSI") fetching...
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bsi-1.8.0/lib/relaton_bsi/bsi_bibliography.rb:77:in `include?': no implicit conversion of nil into String (TypeError)
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bsi-1.8.0/lib/relaton_bsi/bsi_bibliography.rb:77:in `block in search_filter'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bib-1.8.0/lib/relaton_bib/hit_collection.rb:61:in `select!'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bib-1.8.0/lib/relaton_bib/hit_collection.rb:61:in `select'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bsi-1.8.0/lib/relaton_bsi/bsi_bibliography.rb:73:in `search_filter'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bsi-1.8.0/lib/relaton_bsi/bsi_bibliography.rb:102:in `bib_get1'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bsi-1.8.0/lib/relaton_bsi/bsi_bibliography.rb:40:in `get'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bsi-1.8.0/lib/relaton_bsi/processor.rb:17:in `get'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-1.8.0/lib/relaton/db.rb:420:in `net_retry'
[metanorma] Error: doc format is not supported for this standard.
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-1.8.0/lib/relaton/db.rb:405:in `new_bib_entry'
[metanorma] Error: html_alt format is not supported for this standard.
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-1.8.0/lib/relaton/db.rb:385:in `check_bibliocache'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-1.8.0/lib/relaton/db.rb:73:in `fetch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/ref_sect.rb:70:in `fetch_ref'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/ref.rb:162:in `refitem1'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/ref.rb:154:in `refitem'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/ref.rb:213:in `reference1'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/ref_sect.rb:14:in `block (2 levels) in reference'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/ref_sect.rb:14:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/ref_sect.rb:14:in `block in reference'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `new'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `with'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/utils.rb:35:in `noko'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/ref_sect.rb:13:in `reference'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/lists.rb:39:in `ulist'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/utils.rb:14:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.15/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.15/lib/asciidoctor/list.rb:30:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.15/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.15/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.15/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/ref_sect.rb:26:in `block in bibliography_parse'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:394:in `insert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/ref_sect.rb:23:in `bibliography_parse'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/section.rb:90:in `block in section'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `new'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `with'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/utils.rb:35:in `noko'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/section.rb:64:in `section'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/utils.rb:14:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.15/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.15/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.15/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.15/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/ref_sect.rb:26:in `block in bibliography_parse'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:394:in `insert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/ref_sect.rb:23:in `bibliography_parse'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/section.rb:79:in `block in section'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `new'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `with'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/utils.rb:35:in `noko'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/section.rb:64:in `section'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/utils.rb:14:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.15/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.15/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.15/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.15/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.15/lib/asciidoctor/document.rb:1013:in `content'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/base.rb:218:in `block in middle'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:394:in `insert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/base.rb:217:in `middle'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/base.rb:189:in `block in makexml1'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `new'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `with'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/utils.rb:35:in `noko'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/base.rb:189:in `makexml1'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/base.rb:195:in `makexml'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/base.rb:161:in `document'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.9.2/lib/asciidoctor/standoc/utils.rb:14:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.15/lib/asciidoctor/document.rb:944:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.15/lib/asciidoctor/convert.rb:119:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.3.2/lib/metanorma/input/asciidoc.rb:24:in `process'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.3.2/lib/metanorma/processor.rb:24:in `input_to_isodoc'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.3.2/lib/metanorma/compile.rb:93:in `process_input'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.3.2/lib/metanorma/compile.rb:26:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.8/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.8/lib/metanorma/cli/compiler.rb:30:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.8/lib/metanorma/cli/compiler.rb:35:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.8/lib/metanorma/cli/site_generator.rb:81:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.8/lib/metanorma/cli/site_generator.rb:28:in `block in generate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.8/lib/metanorma/cli/site_generator.rb:28:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.8/lib/metanorma/cli/site_generator.rb:28:in `generate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.8/lib/metanorma/cli/site_generator.rb:23:in `generate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.8/lib/metanorma/cli/commands/site.rb:25:in `generate'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-hollaback-0.2.0/lib/thor/hollaback.rb:62:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-hollaback-0.2.0/lib/thor/hollaback.rb:62:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.8/lib/metanorma/cli.rb:34:in `start'
	from /__enclose_io_memfs__/local/metanorma:218:in `<main>'

</p>
</details>

CI Log: https://github.com/metanorma/packed-mn/runs/2624726549?check_suite_focus=true

## Steps to reproduce

 - clone https://github.com/metanorma/mn-samples-bsi
 - run `metanorma site generate --agree-to-terms`

**Comment by andrew2net** [comment]
Fixed it but it follows from the message `[relaton-bsi] ("BSI") fetching...` that the reference hasn't document number, so no documents could be found.

**Comment by ronaldtse** [comment]
@CAMOBAP please close if fixed. 

@andrew2net in any case it shouldn’t crash though. Thanks!

**Comment by CAMOBAP** [comment]
Thanks @andrew2net I just restarted CI to confirm the fix

**Comment by andrew2net** [comment]
> @andrew2net in any case it shouldn’t crash though. Thanks!

@ronaldtse it doesn't crash anymore

**Comment by CAMOBAP** [comment]
@andrew2net thanks, I can confirm (both macos and windows passed)
