### ISSUE TITLE
Plus sign in queries

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bsi#11]
The following are distinct documents:

*  "BS EN ISO 14044:2006"
*  "BS EN ISO 14044:2006+A1:2018"
*  "BS EN ISO 14044:2006+A2:2020"

A query for  "BS EN ISO 14044:2006" returns "BS EN ISO 14044:2006+A2:2020". A query for "BS EN ISO 14044:2006+A2:2020" or for "BS EN ISO 14044:2006+A1:2018" does not return anything.

BSI's choice to use plus signs to notate addenda is unfortunate, but we need to deal with it.

Is impacting https://github.com/metanorma/bs-202000

**Comment by andrew2net** [comment]
@opoudjis the https://shop.bsigroup.com/search doesn't find "BS EN ISO 14044:2006" document:
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/5623890/149975809-1e77f0cd-ed74-4d1c-86b6-4e8c2422c917.png">
It only returns "BS EN ISO 14044:2006+A1:2018" and "BS EN ISO 14044:2006+A2:2020".
Should we return nil for "BS EN ISO 14044:2006" reference?

**Comment by opoudjis** [comment]
I assumed "BS EN ISO 14044:2006" existed. I guess in the case of "BS EN ISO 14044:2006", return the most recent match, but treat it as an instance?

**Comment by andrew2net** [comment]
Usually, we return the most recent match when a reference is without a year.
What does "+A1" mean?

**Comment by ronaldtse** [comment]
> What does "+A1" mean?

Normally an Amendment (and a Correction) is published separately from the standard. "+A1" means that the standard incorporates the Amendment document, i.e. the document is actually a collection of two documents put into one.
