### ISSUE TITLE
BSI data source issue: BS ISO 55000:2014 fetching wrong result

### ISSUE THREAD

**Issue by Intelligent2013** [relaton/relaton-bsi#14]
The code:
```
item = RelatonBsi::BsiBibliography.get("BS ISO 55000:2014")
```
returns `BS ISO 55000:2014` with ` Combined IAM` addon:
```
[relaton-bsi] ("BS ISO 55000:2014") fetching...
[relaton-bsi] ("BS ISO 55000:2014") found BS ISO 55000:2014 Combined IAM
```

but in BSI Shop there is `BS ISO 55000:2014`:
![image](https://user-images.githubusercontent.com/5559926/158948336-dbf670a1-c0d6-4c17-b5f1-7a94c15f5fe5.png)

**Comment by andrew2net** [comment]
fixed in v 1.11.1
