### ISSUE TITLE
BS 25999-1: returns `(German)` version

### ISSUE THREAD

**Issue by Intelligent2013** [relaton/relaton-bsi#16]
Source ticket: https://github.com/metanorma/mnconvert/issues/129

The code
```ruby
item = RelatonBsi::BsiBibliography.get("BS 25999-1")
```
returns Germain version `BS 25999-1:2006 (German)`:
```
[relaton-bsi] ("BS 25999-1") fetching...
[relaton-bsi] ("BS 25999-1") found BS 25999-1:2006 (German)
```
but https://shop.bsigroup.com/search?query=BS+25999-1&type=products returns version without language also:
![image](https://user-images.githubusercontent.com/5559926/160294787-2f3ecde4-4794-4be4-8c54-34d9b1d647de.png)

**Comment by andrew2net** [comment]
@Intelligent2013 I'm unable to reproduce the latest version. Could you try it with version 1.11.1?

**Comment by Intelligent2013** [comment]
@andrew2net no issue with version 1.11.1. Thanks!
