### ISSUE TITLE
Add doctype "expert-commentary" to BSI documents and model

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bsi#19]
There is a doctype called "expert-commentary" ("Expert commentary") that is published.

The identifier is as:
```
{base ID} ExComm
```

Just like:
* BS EN ISO 13485:2016 ExComm
* BS 7273-4:2015+A1:2021 ExComm

This is a blocker to:
* https://github.com/metanorma/metanorma-bsi/issues/241 (see for more info)

**Comment by ronaldtse** [comment]
Actually this is also a BUG:

```
* [[[BS_7273_4_2015,hidden(BS 7273-4:2015)]]]
```

Currently fetches
<img width="159" alt="Screenshot 2023-02-16 at 3 19 46 PM" src="https://user-images.githubusercontent.com/11865/219295158-e2145b88-74e5-471b-96c4-4ef672944f08.png">

Relaton fetch:
```sh
$ bundle exec relaton fetch "BS 7273-4:2015"
[relaton-bsi] ("BS 7273-4:2015") fetching...
[relaton-iso-bib] WARNING: invalid doctype: publication
[relaton-iso-bib] Allowed doctypes are: british-standard, draft-for-development, published-document, privately-subscribed-standard, publicly-available-specification, flex-standard, international-standard, technical-specification, technical-report, guide, international-workshop-agreement, industry-technical-agreement, standard, european-workshop-agreement, fast-track-standard
[relaton-bsi] ("BS 7273-4:2015") found BS 7273-4:2015 ExComm (Fire)
[relaton-iso-bib] WARNING: invalid doctype: publication
[relaton-iso-bib] Allowed doctypes are: british-standard, draft-for-development, published-document, privately-subscribed-standard, publicly-available-specification, flex-standard, international-standard, technical-specification, technical-report, guide, international-workshop-agreement, industry-technical-agreement, standard, european-workshop-agreement, fast-track-standard
<bibdata type="standard" schema-version="v1.2.1">
  <fetched>2023-02-16</fetched>
  <title type="title-main" format="text/plain" language="en" script="Latn">Expert Commentary on BS 7273‑4:2015, Code of practice for the operation of fire protection measures</title>
  <title type="main" format="text/plain" language="en" script="Latn">Expert Commentary on BS 7273‑4:2015, Code of practice for the operation of fire protection measures</title>
  <uri type="src">https://shop.bsigroup.com/products/expert-commentary-on-bs-7273-4-2015-code-of-practice-for-the-operation-of-fire-protection-measures</uri>
  <docidentifier type="BSI" primary="true">BS 7273-4:2015 ExComm (Fire)</docidentifier>
  <date type="published">
    <on>2017-05-01</on>
  </date>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>British Standards Institution</name>
      <abbreviation>BSI</abbreviation>
      <uri>https://www.bsigroup.com/</uri>
    </organization>
  </contributor>
  <language>en</language>
  <script>Latn</script>
  <abstract format="text/plain" language="en" script="Latn"/>
  <status>
    <stage>Current</stage>
  </status>
  <copyright>
    <from>2017</from>
    <owner>
      <organization>
        <name>British Standards Institution</name>
        <abbreviation>BSI</abbreviation>
        <uri>https://www.bsigroup.com/</uri>
      </organization>
    </owner>
  </copyright>
  <place>London</place>
  <ext schema-version="v1.0.0">
    <doctype>publication</doctype>
    <editorialgroup>
      <technical-committee>FSH/12</technical-committee>
    </editorialgroup>
    <ics>
      <code>13.220.20</code>
      <text>Fire protection</text>
    </ics>
    <structuredidentifier>
      <project-number>BS 7273-4:2015 ExComm (Fire)</project-number>
    </structuredidentifier>
  </ext>
</bibdata>
```

It's supposed to find the standard, not the expert commentary 😉

**Comment by ronaldtse** [comment]
@andrew2net this needs to be fixed before Feb 22. Thanks!

**Comment by andrew2net** [comment]
> * BS EN ISO 13485:2016 ExComm
> * BS 7273-4:2015+A1:2021 ExComm

@ronaldtse BSI has "BS EN ISO 13485 Expert Commentary" and "BS 7273-4:2015+A1:2021 ExComm"
https://knowledge.bsigroup.com/products/expert-commentary-for-bs-en-iso-13485-2016/standard
https://knowledge.bsigroup.com/products/code-of-practice-for-the-operation-of-fire-protection-measures-actuation-of-release-mechanisms-for-doors-2/standard
They can be fetched with `relaton fetch 'BS EN ISO 13485 Expert Commentary'` and `relaton fetch 'BS 7273-4:2015+A1:2021 ExComm'` references respectively.
Do you mean we need to fetch all the "Expert Commentary" document usint short "ExComm" in reference?

**Comment by andrew2net** [comment]
> It's supposed to find the standard, not the expert commentary 😉

@ronaldtse BSI only found two standards `BS 7273-4:2015+A1:2021 - SET` and `BS 7273-4:2015+A1:2021`, two publications `BS 7273-4:2015+A1:2021 ExComm` and `BS 7273-4:2015 ExComm (Fire)`, and one article `BS 7273-4`.
https://knowledge.bsigroup.com/search?page=1&query=BS+7273-4%3A2015&type=all
Which one of these documents should the relaton-bsi fetch with the `BS 7273-4:2015` reference?

**Comment by ronaldtse** [comment]
This is clearly a problem, that the bibliographic items do not exist. We will report back to BSI.

**Comment by ronaldtse** [comment]
In any case, allow us to find the `ExComm` first?

**Comment by andrew2net** [comment]
@ronaldtse fetching "Expert commentary" documents implemented in v 1.14.4
FYI there is no document "BS EN ISO 13485:2016 ExComm". There is "BS EN ISO 13485 ExComm" without a year.

**Comment by ronaldtse** [comment]
@andrew2net this is not good but we will report to BSI. Thanks!

**Comment by ronaldtse** [comment]
This is considered done, I will raise to BSI regarding the ExComm without year.
