### ISSUE TITLE
docnumber missing from output

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-bsi#20]
e.g. for BS 5499-4:2013. I rely on docnumber to sort references, as the extracted numeric component of standards identifiers.

**Comment by andrew2net** [comment]
@opoudjis fixed in v1.14.3

**Comment by andrew2net** [comment]
@opoudjis fixed in v 1.14.4

**Comment by opoudjis** [comment]
Sorry, no year either. 2050 not 2050:2011.

**Comment by andrew2net** [comment]
@opoudjis fixed in v 1.14.5
