### ISSUE TITLE
Document types of identifiers and documents supported by relaton-bsi

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bsi#29]
For relaton.org

**Comment by ronaldtse** [comment]
Document types

## British Standards

### General

* BS

### Adoptions

* BS EN
* BS ISO, BS IEC
* BS EN ISO, BS EN IEC, BS EN ISO/IEC

## Published Documents

### General

* PD

### Adoptions

* PD CEN TR
* PD IEC TR
* PD ISO PAS, PD ISO TR

## Publicly Available Specifications

* PAS

## Flex

* Flex

## Amendments

* Like "BS 7273-4:2015+A1:2021"

## Expert Commentary

* Like "BS EN ISO 13485:2016+A11:2021 EC"

**Comment by andrew2net** [comment]
Added the relaton-bsi page to the PR https://github.com/relaton/relaton.github.io/pull/53
