### ISSUE TITLE
Compilation failure on fetching "BS EN ISO 9001"

### ISSUE THREAD

**Issue by manuel489** [relaton/relaton-bsi#5]
Adoc:
````
* [[[ref_32,BS EN ISO 9001]]], _Quality management systems – Requirements_
````

Error message:
````
...
[relaton-bsi] ("BS EN ISO 9001") fetching...
C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/relaton-bsi-1.9.0/lib/relaton_bsi/scrapper.rb:124:in `fetch_docid': undefined method `[]' for nil:NilClass (NoMethodError)
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/relaton-bsi-1.9.0/lib/relaton_bsi/scrapper.rb:78:in `parse_page'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/relaton-bsi-1.9.0/lib/relaton_bsi/hit.rb:11:in `fetch'
...
````

**Comment by ronaldtse** [comment]
BSI has updated their shop website and maybe this is one of the new bugs.

**Comment by Intelligent2013** [comment]
Additional cases:
1. 
```ruby
it_collection = RelatonBsi::BsiBibliography.search("BS EN ISO 8848")
```
return the document `BS EN ISO 8848:2017`.

2. The example from readme:
```ruby
it_collection = RelatonBsi::BsiBibliography.search("BS EN ISO 8848:2021")
```
doesn't return anything. But this standard can be found via search on site https://shop.bsigroup.com/products/small-craft-remote-mechanical-steering-systems

3. 
```ruby
hit_collection = RelatonBsi::BsiBibliography.search("BS EN ISO 8848:2017")
```
return the document `BS EN ISO 13929:2017 - TC`.

**Comment by ronaldtse** [comment]
The new BSI site uses GraphQL, we should use that.

**Comment by andrew2net** [comment]
> BSI has updated their shop website and maybe this is one of the new bugs.

BSI has updated its website in August and we've been supporting the update since then. This issue was caused because the `BS EN ISO 9001` document doesn't have an ISBN identifier. It's fixed in v 1.9.2.

> The new BSI site uses GraphQL, we should use that.

The new site uses Algolia, we've been using it since the update.

**Comment by andrew2net** [comment]
@Intelligent2013 
> Additional cases: 1.
> 
> ```ruby
> it_collection = RelatonBsi::BsiBibliography.search("BS EN ISO 8848")
> ```
> 
> return the document `BS EN ISO 8848:2017`.

This method returns a collection of matched documents and yes the second document `hit_collection[1]` is `BS EN ISO 8848:2017`. If you need a specific document please use the `RelatonBsi::BsiBibliography#get` [method](https://github.com/relaton/relaton-bsi#get-standard-by-code-and-year).

> 
> 1. The example from readme:
> 
> ```ruby
> it_collection = RelatonBsi::BsiBibliography.search("BS EN ISO 8848:2021")
> ```
> 
> doesn't return anything. But this standard can be found via search on site https://shop.bsigroup.com/products/small-craft-remote-mechanical-steering-systems
> 

Again, the `RelatonBsi::BsiBibliography#search` method returns a collection, not specific document. At the time the README was maid it returned a collection of 2 documents an only 1 now. So today the `hit_collection[1]` returns `nil` but `hit_collection[0].fetch` returns desiarble document. I reccomed to use `get` insted `serch` to obtain specific docuent.

> 
> ```ruby
> hit_collection = RelatonBsi::BsiBibliography.search("BS EN ISO 8848:2017")
> ```
> 
> return the document `BS EN ISO 13929:2017 - TC`.

This is the same as the 2 above.

**Comment by andrew2net** [comment]
@ronaldtse @Intelligent2013 could we close this issue?

**Comment by manuel489** [comment]
I have confirmed that issue is fixed.

**Comment by Intelligent2013** [comment]
@andrew2net yes, thanks!
