### ISSUE TITLE
Support PAS standards

### ISSUE THREAD

**Issue by Intelligent2013** [relaton/relaton-bsi#6]
@andrew2net as titled.
Source:  https://github.com/metanorma/mn-samples-bsi/issues/67 (1.11)

Example: PAS 2050:2011
https://shop.bsigroup.com/search?query=PAS+2050%3A2011 returns two links.
but:
```ruby
hit_collection = RelatonBsi::BsiBibliography.search("PAS 2050:2011")
```
doesn't return anything.

I can't assign this issue to @andrew2net.

**Comment by Intelligent2013** [comment]
https://shop.bsigroup.com/search?query=PAS+2050%3A2011 returns two documents:
- PAS 2050:2011 'Specification for the assessment of the life cycle greenhouse gas emissions of goods and services'
- PAS 2050-2:2012 'Assessment of life cycle greenhouse gas emissions - Supplementary requirements for the application of PAS 2050:2011 to seafood and other aquatic food products'


```ruby
hit_collection = RelatonBsi::BsiBibliography.search("PAS 2050:2011")
```
returns PAS 2050-2:2012.
But expected result is PAS 2050:2011.

**Comment by ronaldtse** [comment]
@Intelligent2013 you have access to assignments to the Relaton repos now if you accept the invitation. Thanks.

**Comment by andrew2net** [comment]
@Intelligent2013 the method `RelatonBsi::BsiBibliography#search` returns a collection of the documents from the search result page. To get particular document please use `RelatonBsi::BsiBibliography#get` method.

**Comment by andrew2net** [comment]
@ronaldtse @Intelligent2013 could we close this issue?

**Comment by Intelligent2013** [comment]
@andrew2net yes, thanks! It's working ok now.
